.github/workflows/assign-issues-to-projects.yml, .github/workflows/codeql-analysis.yml
Added worflow for assigning new issues to the team platform GitHub project. 
Added codeQL workflow
=> aded two workflows

src/Altinn.Notifications.Email/Altinn.Notifications.Email.csproj, src/Altinn.Notifications.Email/Configuration/CustomTelemetryInitializer.cs, src/Altinn.Notifications.Email/Configuration/KeyVaultSettings.cs, src/Altinn.Notifications.Email/Health/HealthCheck.cs, src/Altinn.Notifications.Email/Health/HealthTelemetryFilter.cs, src/Altinn.Notifications.Email/Program.cs, src/Altinn.Notifications.Email/Properties/launchSettings.json
Application insights with support for telemetry logging from background services added. 
Basic health check implemented. Will be extended once Kafka is in place. 
- altinn/altinn-notifications#151
=> added support for application insights and health check

src/Altinn.Notifications.Email/Altinn.Notifications.Email.csproj, src/Altinn.Notifications.Email/Configuration/KeyVaultSettings.cs, src/Altinn.Notifications.Email/Program.cs, src/Altinn.Notifications.Email/Startup/ApplicationLogging.cs
- Simplified configuration
- Enabled Nullable and fixed warnings
- Moved Logging setup to separate class
=> Program cleaning

.github/workflows/build-and-analyze.yml, README.md, setup-kafka.yml
- Updated test workflow to include a kafka image
- Added script for setting up kafka 
- Documented how to set up locally kafka in readme
=> setup for kafka included in workflow and docs

src/Altinn.Notifications.Email.Core/Configuration/ServiceCollectionExtensions.cs, src/Altinn.Notifications.Email/appsettings.json
added missing service registration
=> added missing service registration

src/Altinn.Notifications.Email.Core/Configuration/ServiceCollectionExtensions.cs, src/Altinn.Notifications.Email.Core/Configuration/TopicSettings.cs, src/Altinn.Notifications.Email.Core/DateTimeService.cs, src/Altinn.Notifications.Email.Core/IDateTimeService.cs, src/Altinn.Notifications.Email.Core/SendNotificationOperationIdentifier.cs, src/Altinn.Notifications.Email.Core/Sending/SendingService.cs, src/Altinn.Notifications.Email.Core/Status/StatusService.cs, src/Altinn.Notifications.Email.Integrations/Configuration/KafkaSettings.cs, src/Altinn.Notifications.Email.Integrations/Consumers/EmailSendingAcceptedConsumer.cs, src/Altinn.Notifications.Email.Integrations/Consumers/KafkaConsumerBase.cs, src/Altinn.Notifications.Email.Integrations/Consumers/SendEmailQueueConsumer.cs, src/Altinn.Notifications.Email/appsettings.json, test/Altinn.Notifications.Email.IntegrationTests/Integrations/EmailOperationConsumerTests.cs, test/Altinn.Notifications.Email.Tests/Email.Core/TestingStatus/SendNotificationOperationIdentifierTests.cs, test/Altinn.Notifications.Email.Tests/Email.Core/TestingStatus/StatusServiceTests.cs
- added datetime service
- removed T from kafka consumer base
- delay for 8 secs before checking comms service status
- removed retry topic for sending accepted
- altinn/altinn-notifications#152
=> Delay before retrieving send status from comms service

src/Altinn.Notifications.Email.Integrations/Producers/CommonProducer.cs
- altinn/altinn-notifications#428
=> log but dont throw producer exception

src/Altinn.Notifications.Email/Program.cs
-  Altinn/altinn-notifications/issues/289
=> disable kafka health check

src/Altinn.Notifications.Email/Program.cs
Removed unstable health checks for now
- altinn/altinn-notifications#268
=> removed integration health checks

setup-kafka.yml
bugfix for failing config after latest kafdrop upgrade
=> removed  -Xss180K for kafdrop setup

src/Altinn.Notifications.Email.Integrations/Clients/EmailServiceClient.cs
Catching RequestFailedException  when checking status of operation id
=> catch RequestFailedException in emailClient #GCPActive

src/Altinn.Notifications.Email/Health/HealthTelemetryFilter.cs
Conditional clean up
Improved readability by cleaning up a conditional
- #{issue number}
=> Improved readability by cleaning up a conditional

.github/workflows/build-and-analyze.yml, .github/workflows/codeql-analysis.yml, Dockerfile, src/Altinn.Notifications.Email.Core/Altinn.Notifications.Email.Core.csproj, src/Altinn.Notifications.Email.Integrations/Altinn.Notifications.Email.Integrations.csproj, src/Altinn.Notifications.Email/Altinn.Notifications.Email.csproj, test/Altinn.Notifications.Email.IntegrationTests/Altinn.Notifications.Email.IntegrationTests.csproj, test/Altinn.Notifications.Email.Tests/Altinn.Notifications.Email.Tests.csproj
Upgraded application to .NET 8
- N/A
=> upgraded solution to .net 8

src/Altinn.Notifications.Email.Integrations/Configuration/KafkaSettings.cs, src/Altinn.Notifications.Email.Integrations/Configuration/SharedClientConfig.cs, src/Altinn.Notifications.Email.Integrations/Consumers/KafkaConsumerBase.cs, src/Altinn.Notifications.Email.Integrations/Producers/CommonProducer.cs
- Consumer groups per consumer type
- Retention time set on topic generation
- altinn/altinn-notifications#319
=> Modified kafka config

src/Altinn.Notifications.Email/appsettings.json
Whitespace in appsettings.json removed
=> removed space in property name

src/Altinn.Notifications.Email/Altinn.Notifications.Email.csproj, src/Altinn.Notifications.Email/Program.cs
Changed library used to support sending telemetry to application insights
=> changed library used for application insights

src/Altinn.Notifications.Email.Integrations/Altinn.Notifications.Email.Integrations.csproj, src/Altinn.Notifications.Email/Altinn.Notifications.Email.csproj, test/Altinn.Notifications.Email.IntegrationTests/Altinn.Notifications.Email.IntegrationTests.csproj, test/Altinn.Notifications.Email.Tests/Altinn.Notifications.Email.Tests.csproj
=> Bump minor updates to dependencies

.github/workflows/container-scan.yml
Replaces the [deprecated GitHub action Azure/container-scan](https://github.com/Azure/container-scan?tab=readme-ov-file#deprecation-notice). Ref. [Slack discussion on the subject](https://digdir.slack.com/archives/C079SER1G21/p1729519424373009) 
- #{issue number}
=> Replace azure container scan

Dockerfile
Reverts Altinn/altinn-notifications-email#103
We will update the .Net framework separately.
=> Revert "Update mcr.microsoft.com/dotnet/sdk Docker tag to v9"

.github/workflows/build-and-analyze.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container-scan.yml
https://github.com/Altinn/team-core-private/issues/210?issue=Altinn%7Cteam-core-private%7C216
=> Add full semver to actions
